name: CI
on: [push]

jobs:
  job-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: print date with ubuntu
      run: date
  job-windows:
    runs-on: windows-latest
    steps:
    - name: print date with windows
      run: Get-Date
    
      
